bugfix: prevent traceback if element is None
Following traceback would be produced for certain repos:

```
...
  File "/usr/lib/python3.6/site-packages/spacewalk/server/importlib/
backend.py", line 671, in lookupEVRs
    for evr in sorted(evrHash.keys(), key=lambda x: (x[0] if x[0] != '' else 
None, x[1], x[2])):
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```